'use strict'
const express = require("express")
const userControler= require('../Controlers/user.controler')
var md_auntentication = require('../Middlewares/authenticated')
var api = express.Router()
api.post('/registerUser/:idUser', userControler.registerUser)
api.post('/register', userControler.register)
api.post('/login',userControler.login)
api.delete('/deleteUser',md_auntentication.ensureAuth,userControler.userDelete)
api.put('/updateUser/:id',md_auntentication.ensureAuth,userControler.userUpdate)
api.get('/listCategories',md_auntentication.ensureAuth,userControler.listCategories)
api.post('/registerCategory',md_auntentication.ensureAuth,userControler.registerCategory)
api.post('/registerProduct',md_auntentication.ensureAuth,userControler.registerProduct)
api.put('/updateCategory',md_auntentication.ensureAuth,userControler.updateCategory)
api.put('/updateProduct',md_auntentication.ensureAuth,userControler.updateProduct)
api.delete('/deleteCategory',md_auntentication.ensureAuth,userControler.deleteCategory)
api.get('/listProduct',userControler.listProduct)
api.get('/listProductName', userControler.listProductName)
module.exports = api;
